### ISSUE TITLE
Implement chatops for deployment

### ISSUE THREAD

**Issue by cybersiddhu** [dictybase-docker/developer-docs#157]
#138

**Comment by erichartline** [comment]
Keeping both of us added -- I am setting up chatops for issues, Sidd is looking at options for PRs.

**Comment by erichartline** [comment]
`slash-command-dispatch` works perfectly for issue comments and comments in PRs into `master`, but it breaks in PRs into `develop`. Examples in [this repo](https://github.com/dictybase-playground/github-actions-experiments).

**Comment by erichartline** [comment]
Two files are necessary for this to work. Here's how we would set this up for backend software.

In the first config, the `repository` value is included to show how we could set up a slash command processor repository. This first config file would be included in the application repository, and the second config file would be placed in the processor repository. If we don't want to set up a separate repo to process the commands then both workflows would need to be included in the same repo.

chatops.yml
```yaml
name: Slash Command Dispatch
on:
  issue_comment:
    types: [created]
jobs:
  dispatch:
    runs-on: ubuntu-latest
    steps:
      - name: Dispatch deploy slash command
        id: deploy
        uses: peter-evans/slash-command-dispatch@v2
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          reaction-token: ${{ secrets.REPO_ACCESS_TOKEN }}
          commands: deploy
          dispatch-type: workflow
          repository: dictybase-playground/github-actions-experiments
          static-args: |
            repository-name=${{ github.event.repository.name }}
            repository-owner=${{ github.repository_owner }}
            issue-number=${{ github.event.issue.number }}
            html-url=${{ github.event.comment.html_url }}
            comment-id=${{ github.event.comment.id }}
      - name: Edit comment with error message
        if: steps.deploy.outputs.error-message
        uses: peter-evans/create-or-update-comment@v1
        with:
          comment-id: ${{ github.event.comment.id }}
          body: |
            > ${{ steps.deploy.outputs.error-message }}
            > For /deploy commands used in GitHub Issues, you need to specify either specify a `commit` or `branch` to deploy.

            > Example: `/deploy cluster=erickube branch=feature/new-command`

            > For /deploy commands used in pull requests, you can optionally specify a `commit`.
```

deploy-command.yml
```yaml
name: deploy-command
on:
  workflow_dispatch:
    inputs:
      repository-name:
        description: "The name of the repository from which the slash command was dispatched"
        required: true
      repository-owner:
        description: "The owner of the repository from which the slash command was dispatched"
        required: true
      issue-number:
        description: "The issue number in which the slash command was made"
        required: true
      html-url:
        description: "URL where comment was created"
        required: true
      comment-id:
        description: "ID of comment with deploy command"
        required: true
      cluster:
        description: "The cluster to deploy to"
        required: true
      commit:
        description: "Commit ID to deploy"
        required: false
      branch:
        description: "Branch to deploy"
        required: false
jobs:
  prepare-deploy:
    runs-on: ubuntu-latest
    name: Testing deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.repository-owner }}/${{ github.event.inputs.repository-name }}
      - name: download and setup path for github actions binary
        run: |
          mkdir -p github-actions/bin
          curl -L -o github-actions/bin/actions https://github.com/dictybase-docker/github-actions/releases/download/v0.4.1/action_0.4.1_Linux_x86_64
          chmod +x github-actions/bin/actions
          echo "::add-path::$GITHUB_WORKSPACE/github-actions/bin"
      - name: parse deploy command and set vars
        id: vars
        run: actions --log-level debug pcd -f ${GITHUB_EVENT_PATH}
      - name: image build and push
        if: ${{ success() }}
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD  }}
          repository: dictybase/${{ github.event.inputs.repository-name }}
          add_git_labels: true
          tag_with_sha: true
          tag_with_ref: true
          tags: ${{ steps.vars.outputs.image_tag }}
          dockerfile: build/package/Dockerfile
      - name: prepare for deploy
        if: ${{ success() }}
        id: prepare_deploy
        uses: dictybase-docker/prepare-deploy@v1
        with:
          cluster-name: ${{ github.event.inputs.cluster }}
          cluster-zone: "us-central1-a"
          namespace: dictybase
          chart-name: ${{ github.event.inputs.repository-name }}
          chart-path: deployments/charts/${{ github.event.inputs.repository-name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          image-tag: ${{ steps.vars.outputs.image_tag }}
          ref: ${{ steps.vars.outputs.ref }}
          artifact: ${{ github.event.inputs.repository-name }}
          environment: development
  deploy:
    runs-on: ubuntu-latest
    needs: prepare-deploy
    steps:
      - name: check out code
        uses: actions/checkout@v2
      - name: download deployment artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ github.event.inputs.repository-name }}
      - name: download and setup path for github action binary
        run: |
          mkdir -p github-actions/bin
          curl -L -o github-actions/bin/actions https://github.com/dictybase-docker/github-actions/releases/download/v0.4.1/action_0.4.1_Linux_x86_64
          chmod +x github-actions/bin/actions
          echo "::add-path::$GITHUB_WORKSPACE/github-actions/bin"
      - name: extract information from deployment payload
        id: deploy_info
        run: actions --log-level debug sdp -f deployment.json
      - name: set in_progress deployment status
        if: ${{ success() }}
        run: actions --log-level debug -t ${{ secrets.GITHUB_TOKEN }} --owner ${{ github.event.inputs.repository-owner }} -r ${{ github.event.inputs.repository-name }} ds --state in_progress  --deployment_id ${{ steps.deploy_info.outputs.id }} --url ${{ steps.deploy_info.outputs.url }}
      - name: setup google cloud sdk
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "307.0.0"
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.SA_KEY }}
          export_default_credentials: true
      - name: set up helm
        uses: azure/setup-helm@v1
        with:
          version: "v2.16.9"
      - name: get gcloud credentials for k8s cluster
        run: gcloud container clusters get-credentials --project ${{ secrets.PROJECT_ID }} --zone ${{ steps.deploy_info.outputs.zone }} ${{ steps.deploy_info.outputs.cluster }}
      - name: deploy chart
        if: ${{ success() }}
        run: actions --log-level debug dc --name ${{ steps.deploy_info.outputs.chart }} --namespace ${{ steps.deploy_info.outputs.namespace }} --image-tag ${{ steps.deploy_info.outputs.image_tag }} --path ${{ steps.deploy_info.outputs.path }}
      - name: set successful deploy status
        if: ${{ success() }}
        run: actions --log-level debug -t ${{ secrets.GITHUB_TOKEN }} --owner ${{ github.event.inputs.repository-owner }} -r ${{ github.event.inputs.repository-name }} ds --state success  --deployment_id ${{ steps.deploy_info.outputs.id }} --url ${{ steps.deploy_info.outputs.url }}
      - name: set unsuccessful deploy status
        if: ${{ failure() }}
        run: actions --log-level debug -t ${{ secrets.GITHUB_TOKEN }} --owner ${{ github.event.inputs.repository-owner }} -r ${{ github.event.inputs.repository-name }} ds --state error  --deployment_id ${{ steps.deploy_info.outputs.id }} --url ${{ steps.deploy_info.outputs.url }}
  add-reaction:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ github.event.inputs.repository-owner }}/${{ github.event.inputs.repository-name }}
          comment-id: ${{ github.event.inputs.comment-id }}
          reaction-type: hooray
```

**Comment by erichartline** [comment]
Frontend will need some tweaking since we need to change the dockerfile path and image tag based on cluster (i.e. `ericdev-` for `erickube` deployments). The path to Helm chart is also different.

**Comment by erichartline** [comment]
`deploy-command.yml` (for frontend web apps)
```yaml
name: deploy-command
on:
  workflow_dispatch:
    inputs:
      repository-name:
        description: "The name of the repository from which the slash command was dispatched"
        required: true
      repository-owner:
        description: "The owner of the repository from which the slash command was dispatched"
        required: true
      issue-number:
        description: "The issue number in which the slash command was made"
        required: true
      html-url:
        description: "URL where comment was created"
        required: true
      comment-id:
        description: "ID of comment with deploy command"
        required: true
      cluster:
        description: "The cluster to deploy to"
        required: true
      commit:
        description: "Commit ID to deploy"
        required: false
      branch:
        description: "Branch to deploy"
        required: false
jobs:
  prepare-deploy:
    runs-on: ubuntu-latest
    name: Testing deploy
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          repository: ${{ github.event.inputs.repository-owner }}/${{ github.event.inputs.repository-name }}
      - name: download and setup path for github actions binary
        run: |
          mkdir -p github-actions/bin
          curl -L -o github-actions/bin/actions https://github.com/dictybase-docker/github-actions/releases/download/v0.5.1/action_0.5.1_Linux_x86_64
          chmod +x github-actions/bin/actions
          echo "::add-path::$GITHUB_WORKSPACE/github-actions/bin"
      - name: parse deploy command and set vars
        id: vars
        run: |
          actions --log-level debug pcd -f ${GITHUB_EVENT_PATH} --frontend
          if [ ${{ github.event.inputs.cluster }} == "erickube" ]
          then
            echo ::set-output name=docker_path::"docker/eric-dev/Dockerfile"
          elif [ ${{ github.event.inputs.cluster }} == "siddkube" ]
          then
            echo ::set-output name=docker_path::"docker/sidd-dev/Dockerfile"
          else
            exit 1
          fi
      - name: print vars
        run: |
          echo ref: ${{ steps.vars.outputs.ref }}
          echo image_tag: ${{ steps.vars.outputs.image_tag }}
      - name: image build and push
        if: ${{ success() }}
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASSWORD  }}
          repository: dictybase/${{ github.event.inputs.repository-name }}
          add_git_labels: true
          tag_with_sha: true
          tag_with_ref: true
          tags: ${{ steps.vars.outputs.image_tag }}
          dockerfile: ${{ steps.vars.outputs.docker_path }}
      - name: prepare for deploy
        if: ${{ success() }}
        id: prepare_deploy
        uses: dictybase-docker/prepare-deploy@v1
        with:
          cluster-name: ${{ github.event.inputs.cluster }}
          cluster-zone: "us-central1-a"
          namespace: dictybase
          chart-name: ${{ github.event.inputs.repository-name }}
          chart-path: charts/${{ github.event.inputs.repository-name }}
          token: ${{ secrets.GITHUB_TOKEN }}
          image-tag: ${{ steps.vars.outputs.image_tag }}
          ref: ${{ steps.vars.outputs.ref }}
          artifact: ${{ github.event.inputs.repository-name }}
          environment: development
  deploy:
    runs-on: ubuntu-latest
    needs: prepare-deploy
    steps:
      - name: check out code
        uses: actions/checkout@v2
      - name: download deployment artifact
        uses: actions/download-artifact@v2
        with:
          name: ${{ github.event.inputs.repository-name }}
      - name: download and setup path for github action binary
        run: |
          mkdir -p github-actions/bin
          curl -L -o github-actions/bin/actions https://github.com/dictybase-docker/github-actions/releases/download/v0.5.1/action_0.5.1_Linux_x86_64
          chmod +x github-actions/bin/actions
          echo "::add-path::$GITHUB_WORKSPACE/github-actions/bin"
      - name: extract information from deployment payload
        id: deploy_info
        run: actions --log-level debug sdp -f deployment.json
      - name: set in_progress deployment status
        if: ${{ success() }}
        run: actions --log-level debug -t ${{ secrets.GITHUB_TOKEN }} --owner ${{ github.event.inputs.repository-owner }} -r ${{ github.event.inputs.repository-name }} ds --state in_progress  --deployment_id ${{ steps.deploy_info.outputs.id }} --url ${{ steps.deploy_info.outputs.url }}
      - name: setup google cloud sdk
        uses: GoogleCloudPlatform/github-actions/setup-gcloud@master
        with:
          version: "307.0.0"
          project_id: ${{ secrets.PROJECT_ID }}
          service_account_key: ${{ secrets.SA_KEY }}
          export_default_credentials: true
      - name: set up helm
        uses: azure/setup-helm@v1
        with:
          version: "v2.16.9"
      - name: get gcloud credentials for k8s cluster
        run: gcloud container clusters get-credentials --project ${{ secrets.PROJECT_ID }} --zone ${{ steps.deploy_info.outputs.zone }} ${{ steps.deploy_info.outputs.cluster }}
      - name: deploy chart
        if: ${{ success() }}
        run: actions --log-level debug dc --name ${{ steps.deploy_info.outputs.chart }} --namespace ${{ steps.deploy_info.outputs.namespace }} --image-tag ${{ steps.deploy_info.outputs.image_tag }} --path ${{ steps.deploy_info.outputs.path }}
      - name: set successful deploy status
        if: ${{ success() }}
        run: actions --log-level debug -t ${{ secrets.GITHUB_TOKEN }} --owner ${{ github.event.inputs.repository-owner }} -r ${{ github.event.inputs.repository-name }} ds --state success  --deployment_id ${{ steps.deploy_info.outputs.id }} --url ${{ steps.deploy_info.outputs.url }}
      - name: set unsuccessful deploy status
        if: ${{ failure() }}
        run: actions --log-level debug -t ${{ secrets.GITHUB_TOKEN }} --owner ${{ github.event.inputs.repository-owner }} -r ${{ github.event.inputs.repository-name }} ds --state error  --deployment_id ${{ steps.deploy_info.outputs.id }} --url ${{ steps.deploy_info.outputs.url }}
  add-reaction:
    runs-on: ubuntu-latest
    needs: deploy
    steps:
      - name: Add reaction
        uses: peter-evans/create-or-update-comment@v1
        with:
          token: ${{ secrets.REPO_ACCESS_TOKEN }}
          repository: ${{ github.event.inputs.repository-owner }}/${{ github.event.inputs.repository-name }}
          comment-id: ${{ github.event.inputs.comment-id }}
          reaction-type: hooray
```
