### ISSUE TITLE
Add semantic release workflow for creating new tags

### ISSUE THREAD

**Issue by erichartline** [dictybase-docker/developer-docs#158]

**Comment by erichartline** [comment]
```yaml
name: Release
on:
  push:
    branches:
      - master
jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - name: set up node.js
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: check out code
        uses: actions/checkout@v2
      - name: install semantic release
        run: yarn add semantic-release@17.x
      - name: release
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
        run: yarn semantic-release
```
