### ISSUE TITLE
Automerging workflow

### ISSUE THREAD

**Issue by erichartline** [dictybase-docker/developer-docs#185]
For pull request workflows, we need to add an `automerge` step if all tests pass.

Frontend web app example:

```yml
  automerge:
    runs-on: ubuntu-latest
    needs: test
    if: |
      github.actor == 'dependabot[bot]' && 
      startsWith(github.event.pull_request.title, 'build(deps-dev):')
    steps:
      - name: wait for code cov project to pass
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-codecov-project
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: codecov/project
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: wait for codecov patch to pass
        uses: fountainhead/action-wait-for-check@v1.0.0
        id: wait-for-codecov-patch
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          checkName: codecov/patch
          ref: ${{ github.event.pull_request.head.sha || github.sha }}
      - name: merge
        if: steps.wait-for-codecov-project.outputs.conclusion == 'success' && steps.wait-for-codecov-patch.outputs.conclusion == 'success'
        uses: actions/github-script@v3
        with:
          script: |
            github.pulls.merge({
              owner: context.payload.repository.owner.login,
              repo: context.payload.repository.name,
              pull_number: context.payload.pull_request.number,
              merge_method: "rebase"
            })
```

Frontend libraries will have the same approach (automerging dev dependencies).

Backend applications can do automerging for any Dependabot update, as long as all tests and status checks pass.
